on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Documentation Tests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - features: cortex-m
            nodefault: "--no-default-features"
          - features: ""
            nodefault: ""

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.nodefault }} --features=${{ matrix.features }} --manifest-path core/Cargo.toml
